services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: "Europe/London"
      WEBPASSWORD: ""
    volumes:
      - "/home/docker/pihole/etc/pihole:/etc/pihole"
      - "/home/docker/pihole/etc/dnsmasq:/etc/dnsmasq"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
